# Generated by Django 3.0.2 on 2020-02-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='city',
            field=models.CharField(default='Miami', max_length=255),
            preserve_default=False,
        ),
    ]
