# Generated by Django 2.2.4 on 2019-08-23 07:04

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='location',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='media/uploads/trucks/menu'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to='media/uploads/trucks'),
        ),
    ]
