# Generated by Django 3.0.2 on 2020-02-20 19:36

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, default='None', max_length=200, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='truck',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, verbose_name='geolocation'),
        ),
    ]
