# Generated by Django 3.0.2 on 2020-02-19 03:37

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='address',
            field=django_google_maps.fields.AddressField(default='6040 Sunberry Circle', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='1, 1', max_length=100),
            preserve_default=False,
        ),
    ]
