# Generated by Django 3.0.5 on 2020-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200721_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, default='Sorry, this truck has no description', max_length=3000),
        ),
    ]
