# Generated by Django 3.0.2 on 2020-02-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200224_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
