# Generated by Django 3.0.2 on 2020-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200415_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', null=True, upload_to='uploads/trucks/menu-items'),
        ),
    ]
