# Generated by Django 2.0.6 on 2020-01-18 05:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('trucks', '0002_auto_20191206_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', null=True, upload_to='uploads/trucks/profile-pictures'),
        ),
    ]
