# Generated by Django 3.0.2 on 2020-02-20 19:37

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default='None, None', max_length=100, verbose_name='geolocation'),
        ),
    ]
