# Generated by Django 2.2.4 on 2019-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20190823_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='location',
        ),
        migrations.AddField(
            model_name='truck',
            name='menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='uploads/trucks/menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to='uploads/trucks'),
        ),
    ]
