# Generated by Django 3.0.2 on 2020-02-19 01:41

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
