# Generated by Django 3.0.6 on 2020-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200526_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='../media/assets/truck_logo_placeholder.png', upload_to='uploads/trucks/profile-pictures'),
        ),
    ]
