# Generated by Django 3.0.2 on 2020-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200902_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='assets/truck_logo_placeholder.png', upload_to='uploads/trucks/menu-items'),
        ),
    ]
