# Generated by Django 3.0.2 on 2020-02-20 19:40

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200220_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation'),
        ),
    ]
