# Generated by Django 3.0.4 on 2020-03-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200322_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'get_latest_by': 'visited'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='truck_rating'),
        ),
    ]
