# Generated by Django 2.2.5 on 2019-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20190915_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='menu',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
