# Generated by Django 3.0.2 on 2020-02-19 02:48

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_truck_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='city',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='location',
        ),
        migrations.AddField(
            model_name='truck',
            name='address',
            field=django_google_maps.fields.AddressField(default='6040 Sunberry Circle, Florida', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='1,1', max_length=100),
            preserve_default=False,
        ),
    ]
