# Generated by Django 3.0.5 on 2020-09-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200902_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='../media/assets/truck_logo_placeholder.png', upload_to='uploads/trucks/profile-pictures'),
        ),
    ]
