# Generated by Django 3.0.5 on 2020-05-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20200424_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'get_latest_by': ('visited',)},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
