# Generated by Django 3.0.5 on 2020-09-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20200903_2336'),
        ('trucks', '0004_auto_20200908_1501'),
    ]

    operations = [
    ]
