# Generated by Django 3.0.6 on 2020-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20200612_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/tags/icons'),
        ),
    ]
