# Generated by Django 2.2.4 on 2019-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20190919_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/trucks/menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/trucks'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
