# Generated by Django 3.0.2 on 2020-04-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20200323_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenningTime',
        ),
    ]
