# Generated by Django 3.0.5 on 2020-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20200505_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', upload_to='uploads/trucks/menu-items'),
        ),
    ]
