# Generated by Django 3.0.5 on 2020-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_merge_20200915_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='/assets/truck_logo_placeholder.png', upload_to='uploads/trucks/menu-items'),
        ),
    ]
