# Generated by Django 3.0.5 on 2020-07-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20200625_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='available_for_catering',
            field=models.BooleanField(default=False),
        ),
    ]
