# Generated by Django 3.0.2 on 2020-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20200119_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openningtime',
            name='truck',
        ),
        migrations.AddField(
            model_name='truck',
            name='openning_times',
            field=models.ManyToManyField(to='trucks.OpenningTime'),
        ),
    ]
