# Generated by Django 3.0.5 on 2020-09-18 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20200917_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='truck_images')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=1024, null=True)),
                ('truck', models.ForeignKey(help_text='Truck this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trucks.Truck')),
            ],
        ),
    ]
