# Generated by Django 3.0.5 on 2020-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20200511_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='trucks.Tag'),
        ),
    ]
