# Generated by Django 3.0.5 on 2020-07-21 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_auto_20200718_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 21, 23, 8, 48, 47592, tzinfo=utc)),
        ),
    ]
