# Generated by Django 3.0.2 on 2020-05-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_auto_20200511_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='live',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
