# Generated by Django 3.0.5 on 2020-09-19 00:57

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_truckimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='trucks.Truck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
