# Generated by Django 3.0.2 on 2020-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0009_truck_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='tags',
            field=models.ManyToManyField(blank=True, to='trucks.Tag'),
        ),
    ]
