# Generated by Django 3.0.5 on 2020-07-21 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0010_auto_20200721_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
