# Generated by Django 3.0.2 on 2020-01-20 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0011_auto_20200119_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trucks.Truck'),
        ),
        migrations.AlterField(
            model_name='openningtime',
            name='from_hour',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='openningtime',
            name='to_hour',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='openningtime',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='trucks.Truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='title',
            field=models.CharField(default='Title', max_length=120),
            preserve_default=False,
        ),
    ]
