# Generated by Django 3.1.5 on 2021-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0012_truck_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
