# Generated by Django 2.2.7 on 2020-01-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0012_auto_20200119_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuItemCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/trucks/menu-items')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trucks.MenuItem')),
            ],
        ),
    ]
