# Generated by Django 2.2.7 on 2020-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0013_auto_20200123_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='menuitemcombo',
            name='item',
        ),
        migrations.AddField(
            model_name='menuitemcombo',
            name='item',
            field=models.ManyToManyField(related_name='items', to='trucks.MenuItem'),
        ),
    ]
