# Generated by Django 3.1.7 on 2021-04-08 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0013_truck_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
