# Generated by Django 3.1.7 on 2021-04-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0014_auto_20210408_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
