# Generated by Django 2.2.7 on 2020-01-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0015_auto_20200123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='entre',
            field=models.ForeignKey(limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.MenuItem'),
        ),
    ]
