# Generated by Django 3.2 on 2021-04-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0016_auto_20210411_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert'), (5, 'Combo')], default=0),
        ),
    ]
