# Generated by Django 3.0.2 on 2020-01-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0017_auto_20200123_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert'), (5, 'Combo')]),
        ),
    ]
