# Generated by Django 3.1 on 2021-04-25 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0017_alter_menuitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='trucks.truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trucks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'truck')},
            },
        ),
    ]
