# Generated by Django 3.1 on 2021-04-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0018_truckfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='../media/assets/truck_logo_placeholder.png', null=True, upload_to='uploads/trucks/profile-pictures'),
        ),
    ]
