# Generated by Django 3.0.2 on 2020-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0018_auto_20200123_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', null=True, upload_to='uploads/trucks/menu-items'),
        ),
    ]
