# Generated by Django 3.1 on 2021-04-29 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0019_auto_20210428_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, help_text='Leave a description of your experience (optional)', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Review created on'),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Review edited on'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='What do you rate this food truck?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Truck rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
    ]
