# Generated by Django 3.0.2 on 2020-02-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0020_auto_20200124_1316'),
        ('trucks', '0020_auto_20200124_1026'),
    ]

    operations = [
    ]
