# Generated by Django 3.0.2 on 2020-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0021_merge_20200201_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', upload_to='uploads/trucks/menu-items'),
        ),
    ]
