# Generated by Django 3.0.2 on 2020-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0022_auto_20200203_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', upload_to='uploads/trucks/profile-pictures'),
        ),
    ]
