# Generated by Django 3.0.2 on 2020-02-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0023_auto_20200204_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, default='Sorry, this item has no description.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.CharField(blank=True, default='Sorry, this truck has no description', max_length=500),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1.0'), (1.5, '1.5'), (2, '2.0'), (2.5, '2.5'), (3, '3.0'), (3.5, '3.5'), (4, '4.0'), (4.5, '4.5'), (5, '5.0')], verbose_name='rating')),
                ('description', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_edited', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trucks.Truck')),
            ],
        ),
    ]
