# Generated by Django 3.0.2 on 2020-02-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0024_auto_20200206_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='owner',
            new_name='reviewer',
        ),
    ]
