# Generated by Django 3.0.2 on 2020-02-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0025_auto_20200206_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='trucks.Truck'),
        ),
    ]
