# Generated by Django 3.0.2 on 2020-02-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0027_truck_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='desert',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='entre',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='side',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink')]),
        ),
        migrations.CreateModel(
            name='MenuItemCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(blank=True, default='Sorry, this item has no description.', max_length=500, null=True)),
                ('price', models.FloatField(max_length=10)),
                ('image', models.ImageField(blank=True, default='../media/uploads/trucks/profile-pictures/truck_logo_placeholder.png', upload_to='uploads/trucks/menu-items')),
                ('desert', models.ForeignKey(blank=True, limit_choices_to={'type': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desert', to='trucks.MenuItem')),
                ('drink', models.ForeignKey(blank=True, limit_choices_to={'type': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='trucks.MenuItem')),
                ('entre', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='entre', to='trucks.MenuItem')),
                ('side', models.ForeignKey(blank=True, limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side', to='trucks.MenuItem')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='trucks.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deserts', models.ForeignKey(blank=True, limit_choices_to={'type': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deserts', to='trucks.MenuItem')),
                ('drinks', models.ForeignKey(blank=True, limit_choices_to={'type': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='trucks.MenuItem')),
                ('entres', models.ForeignKey(blank=True, limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entres', to='trucks.MenuItem')),
                ('sides', models.ForeignKey(blank=True, limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='trucks.MenuItem')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='trucks.Truck')),
            ],
        ),
    ]
