# Generated by Django 3.0.2 on 2020-02-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0028_auto_20200207_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='deserts',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entres',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='sides',
        ),
    ]
