# Generated by Django 3.0.2 on 2020-02-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0029_auto_20200207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_menu', to='trucks.Truck'),
        ),
    ]
