# Generated by Django 3.0.2 on 2020-02-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0030_auto_20200207_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemcombo',
            name='side',
        ),
        migrations.AddField(
            model_name='menuitemcombo',
            name='side1',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side1', to='trucks.MenuItem'),
        ),
        migrations.AddField(
            model_name='menuitemcombo',
            name='side2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side2', to='trucks.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='trucks.Truck'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert')]),
        ),
        migrations.AlterField(
            model_name='menuitemcombo',
            name='description',
            field=models.CharField(blank=True, default='Sorry, this combo has no description.', max_length=500, null=True),
        ),
    ]
