# Generated by Django 3.0.2 on 2020-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0031_auto_20200207_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entre'), (2, 'Side'), (3, 'Drink'), (4, 'Desert'), (5, 'Combo')]),
        ),
        migrations.DeleteModel(
            name='MenuItemCombo',
        ),
    ]
