# Generated by Django 3.0.2 on 2020-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0033_auto_20200217_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '0.0'), (1, '0.5'), (2, '1.0'), (3, '1.5'), (4, '2.0'), (5, '2.5'), (6, '3.0'), (7, '3.5'), (8, '4.0'), (9, '4.5'), (10, '5.0')], verbose_name='truck_rating'),
        ),
    ]
