# Generated by Django 3.0.2 on 2020-02-17 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0034_auto_20200217_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='disliker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliker', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
