# Generated by Django 3.0.2 on 2020-02-17 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0035_auto_20200217_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='disliker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disliker', to=settings.AUTH_USER_MODEL),
        ),
    ]
