# Generated by Django 3.0.2 on 2020-03-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200301_1846'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.Truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trucks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'truck')},
            },
        ),
    ]
