# Generated by Django 3.0.5 on 2020-07-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='checked',
        ),
    ]
