# Generated by Django 3.0.2 on 2020-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='search_created',
            new_name='created',
        ),
    ]
