# Generated by Django 3.0.5 on 2020-07-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200718_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='created',
            new_name='searched_on',
        ),
    ]
