# Generated by Django 3.0.2 on 2020-02-06 20:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200124_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
