# Generated by Django 3.0.2 on 2020-02-15 22:25

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
