# Generated by Django 3.0.5 on 2020-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/assets/grubtruck.png', null=True, upload_to=''),
        ),
    ]
