# Generated by Django 3.0.5 on 2020-07-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200718_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='term',
            field=models.CharField(max_length=128),
        ),
    ]
