# Generated by Django 3.0.6 on 2020-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200901_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/assets/grubtruck.png', upload_to=''),
        ),
    ]
