# Generated by Django 3.0.2 on 2020-03-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
