# Generated by Django 3.0.6 on 2020-07-19 12:55

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200718_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True),
        ),
    ]
