# Generated by Django 3.0.4 on 2020-03-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200322_0215'),
        ('users', '0005_auto_20200311_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritetruck',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='trucks.Truck'),
        ),
    ]
