# Generated by Django 3.0.6 on 2020-09-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200902_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/assets/grubtruck.png', upload_to='uploads/user/profile-pictures'),
        ),
    ]
