# Generated by Django 3.1 on 2021-04-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210425_0553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckFavorite',
        ),
    ]
