# Generated by Django 3.0.4 on 2020-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly')])),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('endTime', models.TimeField(verbose_name='End Time')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('cancelledDate', models.DateField(blank=True, null=True, verbose_name='Cancelled Date')),
                ('paidAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amount Paid')),
                ('paidDate', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
            ],
        ),
    ]
