# Generated by Django 3.0.6 on 2020-07-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trucks',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='trucks.Truck'),
        ),
        migrations.CreateModel(
            name='CancelledEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
