# Generated by Django 3.0.4 on 2020-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200521_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaidEvent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paidAmt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paidDate',
        ),
    ]
