# Generated by Django 3.0.5 on 2020-09-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20200915_0750'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20200724_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Event organizer', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text="Event organizer's contact number", max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Sorry, this event has no description', help_text='Event description', max_length=3000),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='When does the event end?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='When does the event begin?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event name', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='trucks',
            field=models.ManyToManyField(blank=True, help_text='What trucks are attending?', null=True, related_name='events', to='trucks.Truck'),
        ),
    ]
