# Generated by Django 3.0.5 on 2020-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200724_0347'),
        ('events', '0002_auto_20200721_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Sorry, this event has no description', max_length=3000),
        ),
        migrations.AlterField(
            model_name='event',
            name='trucks',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='trucks.Truck'),
        ),
    ]
