# Generated by Django 3.0.4 on 2020-05-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200521_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Big test event', max_length=120),
            preserve_default=False,
        ),
    ]
