# Generated by Django 3.0.6 on 2020-06-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200526_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end_date',
        ),
    ]
