# Generated by Django 3.0.6 on 2020-07-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200718_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='truck',
            new_name='trucks',
        ),
    ]
