# Generated by Django 3.0.5 on 2020-09-17 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20200915_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImGoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text="Is there anything you'd like to say to the event organizer?", max_length=500)),
                ('event', models.ForeignKey(help_text='Event you are attending', on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(help_text='Who is going?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
