# Generated by Django 3.0.5 on 2020-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_imgoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgoing',
            name='comments',
            field=models.TextField(blank=True, help_text="Is there anything you'd like to say to the event organizer?", max_length=500, null=True),
        ),
    ]
