# Generated by Django 3.0.6 on 2020-05-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200521_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
