# Generated by Django 3.0.5 on 2020-07-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0006_auto_20200625_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField(max_length=10000)),
                ('when', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trucks.Truck')),
            ],
        ),
    ]
