<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-07-19 02:13
=======
# Generated by Django 3.0.5 on 2020-07-19 02:13
>>>>>>> ecaad379b3d9195396ea858502bc201696c435eb

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caterrequest',
            options={'ordering': ('when',)},
        ),
    ]
