# Generated by Django 3.0.6 on 2020-07-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caterrequest',
            options={'ordering': ('when',)},
        ),
    ]
