# Generated by Django 3.0.5 on 2020-07-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_caterrequest_truck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caterrequest',
            options={'ordering': ('-when',)},
        ),
    ]
