# Generated by Django 3.0.5 on 2020-09-18 02:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20200917_1836'),
        ('catering', '0003_caterrequest_requested_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterrequest',
            name='phone',
            field=phone_field.models.PhoneField(default=7723418776, help_text='Your contact number', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='details',
            field=models.TextField(help_text='Tell us about your event', max_length=10000),
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='email',
            field=models.EmailField(help_text="Email you'd like to be reached at", max_length=254),
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='name',
            field=models.CharField(help_text='Your name and/or event name', max_length=128),
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='truck',
            field=models.ForeignKey(help_text='What truck would you like to cater your event?', on_delete=django.db.models.deletion.DO_NOTHING, to='trucks.Truck'),
        ),
    ]
