# Generated by Django 3.1.7 on 2021-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_auto_20200917_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caterrequest',
            name='duration',
            field=models.FloatField(help_text='How many hours do you want catering?'),
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='when',
            field=models.DateTimeField(help_text='When is your event?'),
        ),
    ]
