# Generated by Django 3.0.5 on 2021-04-23 04:19

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0016_auto_20210411_1602'),
        ('catering', '0005_auto_20210411_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterrequest',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='caterrequest',
            name='truck',
            field=models.ForeignKey(help_text='What truck would you like to cater your event?', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cater_requests', to='trucks.Truck'),
        ),
    ]
