# Generated by Django 3.0.5 on 2020-07-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-posted_on',)},
        ),
    ]
