# Generated by Django 3.0.5 on 2020-09-18 05:55

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20200724_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=markdownx.models.MarkdownxField(default=None, help_text='Announcement body', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Announcement title', max_length=256),
        ),
    ]
