# Generated by Django 3.0.5 on 2020-09-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200728_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-posted_on',)},
        ),
    ]
