# Generated by Django 3.0.6 on 2020-09-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200923_1042'),
        ('notifications', '0003_notification_seen'),
    ]

    operations = [
    ]
